#!/usr/bin/env python

import argparse

parser = argparse.ArgumentParser(description="print some files to stdout")
parser.add_argument("--version", action="version", version="%(prog)s 0.1.0")
parser.add_argument("files", nargs="+", help="files to cat")
parser.add_argument(
    "--number",
    "-n",
    action="store_const",
    const=True,
    default=False,
    help="print line numbers",
)
parser.add_argument(
    "--show-ends",
    "-E",
    action="store_const",
    const=True,
    default=False,
    help="display $ at end of each line",
)

args = parser.parse_args()
files = args.files
print_line_numbers = args.number
show_ends = args.show_ends


def add_line_numbers(content):
    count = 0
    updated_content = []

    # TODO (mg): use list-comprehension
    for line in content:
        count += 1
        stripped_line = line.strip("\n")
        updated_content.append(f"{count}\t{stripped_line}")

    return updated_content


def print_lines(content):
    for line in content:
        print(line.strip("\n"))


def print_ends(content):
    updated_content = []

    for line in content:
        line = line.strip("\n") + "$"
        updated_content.append(line)

    return updated_content


if __name__ == "__main__":
    for file in files:
        with open(file, "r") as f:
            if print_line_numbers:
                f = add_line_numbers(f)
            if show_ends:
                f = print_ends(f)
            print_lines(f)
