#!/usr/bin/env python

import argparse


parser = argparse.ArgumentParser(description='print some files to stdout')
parser.add_argument('file', nargs='+', help='files to cat')

args = parser.parse_args()

print(args.file)

for file in args.file:
    with open(file, "r") as f:
        print(f.read())

